spring.application.name=wellcheck

spring.datasource.url=jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.pepvbsdgqqqjupsnaema
spring.datasource.password=WellCheck123!Margel
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8080

spring.security.oauth2.client.registration.google.client-id=545974212372-bs4a8vbc0et63i4cdo4l3s581np8tsb4.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile

app.frontend-url=http://localhost:3000
